### ISSUE TITLE
Jekyll Options for the website 

### ISSUE THREAD

**Issue by ss4ws** [uva-reveal/uva-reveal.github.io#1]
http://arkadianriver.github.io/spectral/
https://mmistakes.github.io/skinny-bones-jekyll/

**Comment by walshbr** [comment]
Are you going to use jekyll for the site? Looking at the repo and based on conversations with you I thought you were just forgoing Jekyll in favor of simple html/css. But should be fine either way. I might have just misunderstood!

**Comment by CHoward345** [comment]
I vote Spectral! :-D

**Comment by jeremyboggs** [comment]
Fixed in 3c590f8864a27fc6158d271096a1c0a9d2108396
